# Generated by Django 4.2 on 2023-04-19 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='channel_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='SubChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='channel_pictures')),
                ('parent_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subchannel_parent_channel', to='my_api.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(default=dict)),
                ('file', models.FileField(upload_to='episode_files/')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('parent_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_parent_channel', to='my_api.channel')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='content',
            field=models.ManyToManyField(blank=True, related_name='contents', to='my_api.content'),
        ),
        migrations.AddField(
            model_name='channel',
            name='subchannels',
            field=models.ManyToManyField(blank=True, related_name='subchannels', to='my_api.subchannel'),
        ),
    ]
