# Generated by Django 4.2 on 2023-04-20 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_rename_content_channel_contents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='file',
        ),
        migrations.RemoveField(
            model_name='content',
            name='metadata',
        ),
    ]
