# Generated by Django 4.2 on 2023-04-20 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0003_remove_content_file_remove_content_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
