# Generated by Django 4.2 on 2023-04-20 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0004_content_file_content_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='subchannels',
        ),
        migrations.AddField(
            model_name='content',
            name='parent_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_parent_channel', to='my_api.channel'),
        ),
        migrations.AddField(
            model_name='subchannel',
            name='parent_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subchannel_parent_channel', to='my_api.channel'),
        ),
    ]
