# Generated by Django 4.2 on 2023-04-20 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0005_remove_channel_contents_remove_channel_subchannels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='parent_channel',
        ),
        migrations.AlterField(
            model_name='subchannel',
            name='parent_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subchannel', to='my_api.channel'),
        ),
        migrations.CreateModel(
            name='TVSHOW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='channel_pictures')),
                ('contents', models.ManyToManyField(blank=True, related_name='tv_show', to='my_api.content')),
                ('parent_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tv_show', to='my_api.channel')),
            ],
        ),
        migrations.CreateModel(
            name='PRESS_MAGAZINES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='channel_pictures')),
                ('contents', models.ManyToManyField(blank=True, related_name='press_magazines', to='my_api.content')),
                ('parent_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='press_magazines', to='my_api.channel')),
            ],
        ),
        migrations.CreateModel(
            name='MUSIC_PODCASTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='channel_pictures')),
                ('contents', models.ManyToManyField(blank=True, related_name='music_podcasts', to='my_api.content')),
                ('parent_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_podcasts', to='my_api.channel')),
            ],
        ),
        migrations.CreateModel(
            name='MOVIES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='channel_pictures')),
                ('contents', models.ManyToManyField(blank=True, related_name='movies', to='my_api.content')),
                ('parent_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='my_api.channel')),
            ],
        ),
        migrations.CreateModel(
            name='LIFESTYLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='channel_pictures')),
                ('contents', models.ManyToManyField(blank=True, related_name='lifestyle', to='my_api.content')),
                ('parent_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle', to='my_api.channel')),
            ],
        ),
        migrations.CreateModel(
            name='KIDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='channel_pictures')),
                ('contents', models.ManyToManyField(blank=True, related_name='kids', to='my_api.content')),
                ('parent_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='my_api.channel')),
            ],
        ),
        migrations.CreateModel(
            name='GAMES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='channel_pictures')),
                ('contents', models.ManyToManyField(blank=True, related_name='games', to='my_api.content')),
                ('parent_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='my_api.channel')),
            ],
        ),
        migrations.CreateModel(
            name='AUDIBLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='channel_pictures')),
                ('contents', models.ManyToManyField(blank=True, related_name='audible', to='my_api.content')),
                ('parent_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audible', to='my_api.channel')),
            ],
        ),
    ]
