# Generated by Django 4.2 on 2023-04-19 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('parent_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.channel')),
            ],
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('subchannel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.subchannel')),
            ],
        ),
        migrations.CreateModel(
            name='Press_and_Magazines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('subchannel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.subchannel')),
            ],
        ),
        migrations.CreateModel(
            name='Music_and_Podcasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('subchannel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.subchannel')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('subchannel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.subchannel')),
            ],
        ),
        migrations.CreateModel(
            name='LifestyleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('subchannel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.subchannel')),
            ],
        ),
        migrations.CreateModel(
            name='Kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('subchannel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.subchannel')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('subchannel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.subchannel')),
            ],
        ),
        migrations.CreateModel(
            name='Audible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('subchannel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.subchannel')),
            ],
        ),
    ]
